name: Update latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '11 4 * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: install CS locale
      run: sudo locale-gen cs_CZ.UTF-8

    - name: Install dependencies
      run: pip install -r api/backend/requirements.txt --upgrade pip