name: Update latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '11 4 * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: install CS locale
      uses: sudo locale-gen cs_CZ.UTF-8

    - name: Install python version
      # use the pyenv-action version 7
      uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6 # pick 3.8.6 verion 
          command: pip install -U pip  # upgrade pip after installing python
      
    - name: create environment
      run: pyenv local 3.8.6 && python -mvenv .venv386

    - name: Install dependencies
      run: pip install -r requirements.txt --upgrade pip

    - name: setup pyenv
      id: pyenv_installation
      uses: "gabrielfalcao/pyenv-action@v7"

    - name: debug pyenv
      run: echo ${{ steps.pyenv_installation.outputs.pyenv_root }}