name: Update latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '11 4 * * *'

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2

    - name: install CS locale
      run: sudo locale-gen cs_CZ.UTF-8

    - name: Install python dependencies
      run: pip3 install -r api/backend/requirements.txt --upgrade pip
    
    - name: Update data
      run: python3 api/backend/create.py

    - name: Install npm dependencies
      run: npm install
    
    - name: Run new build
      run: npm run build
    
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Updated data: ${timestamp}" || exit 0
        git push